version: "3.8"

services:
  wg-easy:
    container_name: wg-easy
    image: weejewel/wg-easy
    restart: unless-stopped
    environment:
      - WG_HOST=your.domain.com  # or your public IP
      - PASSWORD=your_secure_password
    ports:
      - "51820:51820/udp"        # WireGuard VPN
      - "51821:51821/tcp"        # Web UI
    volumes:
      - ./config:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
